[package]
name = "ldr_poc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
rppal = "0.14"
tokio = {version="1", features=["full"]}
serde = {version="1", features=["derive"]}
serde_json = "1"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
